CREATE OR REPLACE DATABASE FIRMABLE_SALES_INTELLIGENCE;

CREATE SCHEMA IF NOT EXISTS FIRMABLE_SALES_INTELLIGENCE.RAW;
CREATE SCHEMA IF NOT EXISTS FIRMABLE_SALES_INTELLIGENCE.CORE;
CREATE SCHEMA IF NOT EXISTS FIRMABLE_SALES_INTELLIGENCE.FEATURES;
CREATE SCHEMA IF NOT EXISTS FIRMABLE_SALES_INTELLIGENCE.AI;
CREATE SCHEMA IF NOT EXISTS FIRMABLE_SALES_INTELLIGENCE.EVAL;
CREATE SCHEMA IF NOT EXISTS FIRMABLE_SALES_INTELLIGENCE.OBSERVABILITY;
CREATE SCHEMA IF NOT EXISTS FIRMABLE_SALES_INTELLIGENCE.APP;

CREATE OR REPLACE WAREHOUSE FIRMABLE_XS
  WAREHOUSE_SIZE='XSMALL'
  AUTO_SUSPEND=60
  AUTO_RESUME=TRUE
  INITIALLY_SUSPENDED=TRUE;

USE DATABASE FIRMABLE_SALES_INTELLIGENCE;

CREATE OR REPLACE FILE FORMAT RAW.JSON_ZSTD_FORMAT
  TYPE=JSON
  COMPRESSION=ZSTD;

CREATE OR REPLACE FILE FORMAT RAW.JSON_GZIP_FORMAT
  TYPE=JSON
  COMPRESSION=GZIP;

CREATE OR REPLACE STAGE RAW.RAW_STAGE
  FILE_FORMAT=RAW.JSON_GZIP_FORMAT;

CREATE OR REPLACE TABLE RAW.SHODAN_EVENTS (
  EVENT_ID NUMBER AUTOINCREMENT,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  SOURCE_FILE VARCHAR,
  RECORD VARIANT
);

CREATE OR REPLACE TABLE OBSERVABILITY.LLM_CALLS (
  REQUEST_ID VARCHAR,
  CALLED_AT TIMESTAMP_NTZ,
  FEATURE VARCHAR,
  MODEL VARCHAR,
  PROMPT_VERSION VARCHAR,
  ACCOUNT_KEY VARCHAR,
  REQUEST_TEXT VARCHAR,
  RESPONSE_TEXT VARCHAR,
  LATENCY_MS NUMBER,
  EST_INPUT_TOKENS NUMBER,
  EST_OUTPUT_TOKENS NUMBER,
  COST_USD NUMBER(18,8),
  DECISION VARCHAR
);

CREATE OR REPLACE TABLE APP.MODEL_CONFIG (
  CONFIG_NAME VARCHAR,
  MODEL_NAME VARCHAR,
  PROMPT_VERSION VARCHAR,
  ENABLED BOOLEAN,
  MAX_ACCOUNTS_PER_RUN NUMBER
);

-- INSERT INTO APP.MODEL_CONFIG
-- VALUES ('ACCOUNT_BRIEF','claude-haiku-4-5','v2',TRUE,25);
