USE DATABASE FIRMABLE_SALES_INTELLIGENCE;
USE WAREHOUSE FIRMABLE_XS;

LIST @RAW.RAW_STAGE;

SELECT $1 AS SAMPLE_RECORD
FROM @RAW.RAW_STAGE/firmable_chunks
(FILE_FORMAT=>RAW.JSON_GZIP_FORMAT)
LIMIT 5;

COPY INTO RAW.SHODAN_EVENTS (SOURCE_FILE, RECORD)
FROM (SELECT METADATA$FILENAME, $1 FROM @RAW.RAW_STAGE/firmable_chunks)
FILE_FORMAT=(FORMAT_NAME='RAW.JSON_GZIP_FORMAT')
ON_ERROR='CONTINUE';

SELECT COUNT(*) FROM RAW.SHODAN_EVENTS;
SELECT * FROM RAW.SHODAN_EVENTS LIMIT 5;
