USE DATABASE FIRMABLE_SALES_INTELLIGENCE;

CREATE OR REPLACE TABLE CORE.INFRASTRUCTURE_EVENTS AS
SELECT
  EVENT_ID, SOURCE_FILE, LOADED_AT,
  RECORD:ip_str::VARCHAR AS IP,
  RECORD:port::NUMBER AS PORT,
  RECORD:transport::VARCHAR AS TRANSPORT,
  NULLIF(ARRAY_TO_STRING(RECORD:hostnames::ARRAY, ','),'') AS HOSTNAMES_TEXT,
  NULLIF(ARRAY_TO_STRING(RECORD:domains::ARRAY, ','),'') AS DOMAINS_TEXT,
  RECORD:org::VARCHAR AS ORGANIZATION,
  RECORD:isp::VARCHAR AS ISP,
  RECORD:asn::VARCHAR AS ASN,
  RECORD:timestamp::TIMESTAMP_NTZ AS SCAN_TIMESTAMP,
  RECORD:location:country_name::VARCHAR AS COUNTRY,
  RECORD:location:country_code::VARCHAR AS COUNTRY_CODE,
  RECORD:location:region_code::VARCHAR AS REGION,
  RECORD:location:city::VARCHAR AS CITY,
  RECORD:http:status::NUMBER AS HTTP_STATUS,
  RECORD:data::VARCHAR AS BANNER,
  RECORD:_shodan:module::VARCHAR AS SHODAN_MODULE,
  RECORD:os::VARCHAR AS OS,
  RECORD AS RAW_RECORD
FROM RAW.SHODAN_EVENTS;

SELECT ORGANIZATION, COUNT(*) EVENTS, COUNT(DISTINCT IP) IPS
FROM CORE.INFRASTRUCTURE_EVENTS
GROUP BY ORGANIZATION
ORDER BY EVENTS DESC
LIMIT 20;
