USE DATABASE FIRMABLE_SALES_INTELLIGENCE;

CREATE OR REPLACE TABLE FEATURES.ACCOUNT_FEATURES AS
WITH base AS (
  SELECT
    COALESCE(NULLIF(ORGANIZATION,''),NULLIF(DOMAINS_TEXT,''),IP) ACCOUNT_KEY,
    ORGANIZATION, IP, PORT, DOMAINS_TEXT, HOSTNAMES_TEXT, COUNTRY,
    SCAN_TIMESTAMP, BANNER, SHODAN_MODULE, HTTP_STATUS, ASN, ISP
  FROM CORE.INFRASTRUCTURE_EVENTS
),
agg AS (
  SELECT
    ACCOUNT_KEY,
    MAX(ORGANIZATION) ORGANIZATION,
    COUNT(*) EVENT_COUNT,
    COUNT(DISTINCT IP) DISTINCT_IPS,
    COUNT(DISTINCT DOMAINS_TEXT) DISTINCT_DOMAIN_GROUPS,
    COUNT(DISTINCT HOSTNAMES_TEXT) DISTINCT_HOSTNAME_GROUPS,
    COUNT(DISTINCT PORT) DISTINCT_PORTS,
    MIN(SCAN_TIMESTAMP) FIRST_SEEN,
    MAX(SCAN_TIMESTAMP) LAST_SEEN,
    COUNT_IF(PORT IN (21,23,445,3389,5900,1433,1521,3306,5432,6379,9200)) RISKY_PORT_COUNT,
    COUNT_IF(PORT IN (21,23)) LEGACY_PROTOCOL_COUNT,
    COUNT_IF(PORT IN (3389,5900,22)) REMOTE_ADMIN_COUNT,
    COUNT_IF(PORT IN (80,443)) WEB_SERVICE_COUNT,
    COUNT_IF(
      LOWER(COALESCE(ORGANIZATION,'')) LIKE ANY ('%amazon%','%aws%','%microsoft%','%azure%','%google%','%alibaba%')
      OR LOWER(COALESCE(ISP,'')) LIKE ANY ('%amazon%','%microsoft%','%google%','%alibaba%')
    ) CLOUD_EVENT_COUNT,
    COUNT_IF(REGEXP_LIKE(LOWER(COALESCE(BANNER,'')),
      'mikrotik|iis|apache|nginx|ftp|telnet|rdp|ssh|smb|vnc|postgres|mysql|redis|elasticsearch'
    )) TECHNOLOGY_SIGNAL_COUNT,
    COUNT_IF(HTTP_STATUS IN (301,302,307,308)) REDIRECT_EVENT_COUNT
  FROM base
  GROUP BY ACCOUNT_KEY
)
SELECT *,
  IFF(CLOUD_EVENT_COUNT>0,TRUE,FALSE) CLOUD_HOSTED_FLAG,
  IFF(RISKY_PORT_COUNT>0,TRUE,FALSE) RISKY_SERVICE_FLAG,
  IFF(LEGACY_PROTOCOL_COUNT>0,TRUE,FALSE) LEGACY_PROTOCOL_FLAG,
  IFF(REMOTE_ADMIN_COUNT>0,TRUE,FALSE) REMOTE_ADMIN_FLAG,
  IFF(TECHNOLOGY_SIGNAL_COUNT>0,TRUE,FALSE) TECHNOLOGY_SIGNAL_FLAG
FROM agg;
