USE DATABASE FIRMABLE_SALES_INTELLIGENCE;

CREATE OR REPLACE TABLE FEATURES.ACCOUNT_SCORES AS
WITH n AS (
  SELECT *,
    LEAST(100,RISKY_PORT_COUNT*15) EXPOSURE_SCORE,
    LEAST(100,REMOTE_ADMIN_COUNT*20+LEGACY_PROTOCOL_COUNT*20) RISK_SCORE,
    LEAST(100,TECHNOLOGY_SIGNAL_COUNT*8) TECHNOLOGY_SCORE,
    LEAST(100,DISTINCT_IPS*5+DISTINCT_PORTS*5) COMPLEXITY_SCORE,
    IFF(CLOUD_HOSTED_FLAG,100,0) CLOUD_SCORE,
    IFF(DATEDIFF('day',LAST_SEEN,CURRENT_TIMESTAMP())<=7,100,
      IFF(DATEDIFF('day',LAST_SEEN,CURRENT_TIMESTAMP())<=30,60,20)) RECENCY_SCORE
  FROM FEATURES.ACCOUNT_FEATURES
),
s AS (
  SELECT *,
    ROUND(
      0.30*EXPOSURE_SCORE +
      0.25*RISK_SCORE +
      0.15*TECHNOLOGY_SCORE +
      0.15*COMPLEXITY_SCORE +
      0.10*CLOUD_SCORE +
      0.05*RECENCY_SCORE,2
    ) PRIORITY_SCORE
  FROM n
)
SELECT *,
  CASE
    WHEN PRIORITY_SCORE>=75 THEN 'HIGH'
    WHEN PRIORITY_SCORE>=50 THEN 'MEDIUM'
    ELSE 'LOW'
  END PRIORITY
FROM s;

SELECT PRIORITY,COUNT(*) ACCOUNTS
FROM FEATURES.ACCOUNT_SCORES
GROUP BY PRIORITY;
