USE DATABASE FIRMABLE_SALES_INTELLIGENCE;

CREATE OR REPLACE VIEW FEATURES.ACCOUNT_EVIDENCE AS
SELECT
  ACCOUNT_KEY, ORGANIZATION, PRIORITY, PRIORITY_SCORE, EVENT_COUNT,
  DISTINCT_IPS, DISTINCT_DOMAIN_GROUPS, DISTINCT_HOSTNAME_GROUPS,
  DISTINCT_PORTS, RISKY_PORT_COUNT, REMOTE_ADMIN_COUNT,
  LEGACY_PROTOCOL_COUNT, TECHNOLOGY_SIGNAL_COUNT, CLOUD_EVENT_COUNT,
  WEB_SERVICE_COUNT, REDIRECT_EVENT_COUNT, FIRST_SEEN, LAST_SEEN,
  OBJECT_CONSTRUCT(
    'risky_port_count',RISKY_PORT_COUNT,
    'remote_admin_count',REMOTE_ADMIN_COUNT,
    'legacy_protocol_count',LEGACY_PROTOCOL_COUNT,
    'technology_signal_count',TECHNOLOGY_SIGNAL_COUNT,
    'cloud_event_count',CLOUD_EVENT_COUNT,
    'distinct_ips',DISTINCT_IPS,
    'distinct_ports',DISTINCT_PORTS,
    'event_count',EVENT_COUNT,
    'last_seen',LAST_SEEN
  ) EVIDENCE
FROM FEATURES.ACCOUNT_SCORES;
