USE DATABASE FIRMABLE_SALES_INTELLIGENCE;

SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AI_FUNCTIONS_USAGE_HISTORY
ORDER BY START_TIME DESC
LIMIT 50;

SELECT SERVICE_TYPE,SUM(CREDITS_USED) CREDITS_USED
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_DAILY_HISTORY
WHERE SERVICE_TYPE='AI_SERVICES'
GROUP BY SERVICE_TYPE;

SELECT * FROM OBSERVABILITY.LLM_CALLS
ORDER BY CALLED_AT DESC;
